name: Code Freeze Check
on:
  pull_request:
    branches:
    - 'dev'
    - 'stage'

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

env:
  LD_API_KEY: ${{ secrets.LD_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Branch
        id: step1
        run: |
          BRANCH='${{ steps.extract_branch.outputs.branch }}'
          echo "$GITHUB_BASE_REF"
          echo "BRANCH=$GITHUB_BASE_REF" >> $GITHUB_ENV
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: execute py script
        run: |
          python ./.github/workflows/code_freeze.py
