name: Check Code Freeze
on:
  pull_request:
    branches:
    - 'dev'
    - 'stage'

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

env:
  LD_API_KEY: ${{ secrets.LD_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Extract branch name
      #   shell: bash
      #   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      #   id: extract_branch
      - name: Set Tier
        id: step1
        run: |
          if [[ "${{ github.ref_name }}" ]]; then
            BRANCH='${{ github.ref_name }}'
          else
            echo "Could not set tier"
            exit
          fi

          echo $BRANCH
          echo "::set-output name=BRANCH::$BRANCH"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          # ref: # branch
          #   my_other_branch
      - name: execute py script
        run: |
          python ./.github/workflows/code_freeze.py
